updated README.md

diff --git a/fly b/fly
--- a/fly
+++ b/fly
@@ -11,7 +11,7 @@ connectionsFolder=
 
 # mfa [ 0 | 1 ]
 #   if your MeshCentral user has multi-factor authentication enabled, set to 1
-mfa=0
+mfa=1
 
 
 
@@ -23,22 +23,24 @@ connectionFile=.connFile.txt
 pidfile=.pidfile
 
 
-# check that meshcmd is present
+# check that meshcmd and jq is present
 if [[ ! -f ./meshcmd ]]; then
-    echo -e "\nCan't find meshcmd\n\n"
+    echo -e "\n\tCan't find meshcmd\n\n"
+    exit 1;
+elif ! [[ $(which jq) ]]; then
+    echo -e "\n\tCan't find jq\n"
+    echo -e "\n\tPlease install jq with 'apt install -y jq'\n\n"
     exit 1;
 fi
 
 if [[ -f ${1} ]]; then
     sourceFile=${1}
+elif [[ -f ${connectionsFolder}/${1} ]]; then
+    sourceFile=${connectionsFolder}/${1}
 else
-    if [[ -f ${connectionsFolder}/${1} ]]; then
-        sourceFile=${connectionsFolder}/${1}
-    else
-        more ${connectionFile}
-        echo -e "\nUnable to find connection file : ${1}\n"
-        exit;
-    fi
+    more ${connectionFile}
+    echo -e "\nUnable to find connection file : ${1}\n"
+    exit;
 fi
 
 localPort=$(jq '.localPort' ${sourceFile})
@@ -76,12 +78,8 @@ fi
 
 cmd="$cmd &"
 
-echo -e "\n\n------------- DEBUGGING ----------------------"
-echo ${cmd}
-echo -e "------------- DEBUGGING ----------------------\n\n"
-
-
 bash -c "${cmd}"
+#echo "bash -c ${cmd} returned $?"
 
 pid=$(ps -ef | grep "${cmd}" | awk '{print $2}')
 
